import os

# SECURITY
API_KEY = os.environ.get('SONGBOOKIT_API_KEY', 'SUPERSECRETKEY')

# POSTGRES SETTINGS
POSTGRES_USER = os.environ.get('SONGBOOKIT_POSTGRES_USER', 'songbookit')
POSTGRES_PASSWORD = os.environ.get('SONGBOOKIT_POSTGRES_PASSWORD', 'password')
POSTGRES_HOST = os.environ.get('SONGBOOKIT_POSTGRES_HOST', 'localhost')
POSTGRES_PORT = os.environ.get('SONGBOOKIT_POSTGRES_PORT', '5432')
POSTGRES_DB = os.environ.get('SONGBOOKIT_POSTGRES_DB', 'postgres')