
ID_NOT_LENGTH_FOUR = "ID_NOT_LENGTH_FOUR"
ID_NOT_LOWERCASE = "ID_NOT_LOWERCASE"

TAG_ID_NOT_EXIST = "TAG_NOT_EXIST"
TAG_TITLE_NOT_EXIST = "TAG_TITLE_NOT_EXIST"
TAG_TITLE_ALREADY_EXIST = "TAG_TITLE_ALREADY_EXIST"


SONG_ID_NOT_EXIST = "SONG_ID_NOT_EXIST"
SONG_TITLE_NOT_EXIST = "SONG_TITLE_NOT_EXIST"
SONG_TITLE_ALREADY_EXIST = "SONG_TITLE_ALREADY_EXIST"



